In [1]:
import pandas as pd

In [2]:
from datasets import load_dataset

dataset = load_dataset("scikit-learn/adult-census-income")  # or "income"

c:\WorkDir\DeepLearningProject\project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['age', 'workclass', 'fnlwgt', 'education', 'education.num', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'capital.gain', 'capital.loss', 'hours.per.week', 'native.country', 'income'],
        num_rows: 32561
    })
})

In [4]:
train_dataset = dataset["train"]

In [5]:
train_dataset.shape

(32561, 15)

In [29]:
dataset_2 = dataset["train"].train_test_split(test_size=0.2, seed=42)

In [30]:
train = dataset_2["train"].to_pandas()
test = dataset_2["test"].to_pandas()

In [31]:
train.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,33,Private,155343,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
1,32,Private,165949,Bachelors,13,Divorced,Machine-op-inspct,Not-in-family,White,Female,0,1590,42,United-States,<=50K
2,18,?,173125,12th,8,Never-married,?,Own-child,White,Female,0,0,24,United-States,<=50K
3,31,Private,118551,9th,5,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
4,60,Self-emp-not-inc,170114,9th,5,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,1672,84,United-States,<=50K

In [32]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 26048 entries, 0 to 26047
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             26048 non-null  int64
 1   workclass       26048 non-null  str
 2   fnlwgt          26048 non-null  int64
 3   education       26048 non-null  str
 4   education.num   26048 non-null  int64
 5   marital.status  26048 non-null  str
 6   occupation      26048 non-null  str
 7   relationship    26048 non-null  str
 8   race            26048 non-null  str
 9   sex             26048 non-null  str
 10  capital.gain    26048 non-null  int64
 11  capital.loss    26048 non-null  int64
 12  hours.per.week  26048 non-null  int64
 13  native.country  26048 non-null  str
 14  income          26048 non-null  str
dtypes: int64(6), str(9)
memory usage: 4.9 MB

In [33]:
train.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,26048.000000,2.604800e+04,26048.000000,26048.000000,26048.000000,26048.000000
mean,38.592330,1.892359e+05,10.085573,1094.080275,87.861448,40.479231
std,13.631103,1.057307e+05,2.575331,7503.738041,404.201863,12.317289
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176278e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.777790e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.362420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [34]:
for col in train.columns[train.dtypes == "str"]:
    print(f"{col} unique values: {train[col].unique()}")

workclass unique values: <ArrowStringArray>
[         'Private',                '?', 'Self-emp-not-inc',
        'State-gov',        'Local-gov',      'Federal-gov',
     'Self-emp-inc',      'Without-pay',     'Never-worked']
Length: 9, dtype: str
education unique values: <ArrowStringArray>
[     'HS-grad',    'Bachelors',         '12th',          '9th',
 'Some-college',         '11th',      'Masters',    'Assoc-voc',
      '7th-8th',   'Assoc-acdm',      '5th-6th',         '10th',
    'Doctorate',  'Prof-school',    'Preschool',      '1st-4th']
Length: 16, dtype: str
marital.status unique values: <ArrowStringArray>
[        'Never-married',              'Divorced',    'Married-civ-spouse',
             'Separated',               'Widowed', 'Married-spouse-absent',
     'Married-AF-spouse']
Length: 7, dtype: str
occupation unique values: <ArrowStringArray>
['Machine-op-inspct',                 '?',      'Adm-clerical',
   'Farming-fishing',    'Prof-specialty', 'Handlers-cleaners',
      'Craft-repair',     'Other-service',             'Sales',
      'Tech-support',  'Transport-moving',   'Exec-managerial',
   'Protective-serv',      'Armed-Forces',   'Priv-house-serv']
Length: 15, dtype: str
relationship unique values: <ArrowStringArray>
['Unmarried', 'Not-in-family', 'Own-child', 'Husband', 'Wife',
 'Other-relative']
Length: 6, dtype: str
race unique values: <ArrowStringArray>
['White', 'Other', 'Black', 'Amer-Indian-Eskimo', 'Asian-Pac-Islander']
Length: 5, dtype: str
sex unique values: <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
native.country unique values: <ArrowStringArray>
[             'United-States',                  'Nicaragua',
                     'Mexico',                       'Laos',
                    'Germany',                'Philippines',
                  'Guatemala',                     'Canada',
                      'China',                          '?',
                'Puerto-Rico',                      'South',
                    'Vietnam',            'Trinadad&Tobago',
                    'England',                      'India',
                       'Iran',                    'Ecuador',
                   'Columbia',                'El-Salvador',
                      'Haiti',                     'Poland',
                     'Greece',                      'Italy',
                    'Hungary',                       'Cuba',
         'Dominican-Republic',                     'France',
                      'Japan', 'Outlying-US(Guam-USVI-etc)',
                 'Yugoslavia',                    'Jamaica',
                     'Taiwan',                   'Cambodia',
                       'Hong',                   'Thailand',
                       'Peru',                    'Ireland',
                   'Honduras',                   'Portugal',
                   'Scotland']
Length: 41, dtype: str
income unique values: <ArrowStringArray>
['<=50K', '>50K']
Length: 2, dtype: str

In [35]:
for col in test.columns[test.dtypes == "str"]:
    print(f"{col} unique values: {test[col].unique()}")

workclass unique values: <ArrowStringArray>
[         'Private',                '?', 'Self-emp-not-inc',
      'Federal-gov',     'Self-emp-inc',        'Local-gov',
        'State-gov',     'Never-worked',      'Without-pay']
Length: 9, dtype: str
education unique values: <ArrowStringArray>
['Some-college',      'HS-grad',    'Assoc-voc',    'Bachelors',
      '7th-8th',  'Prof-school',         '10th',    'Doctorate',
         '11th',         '12th',      'Masters',          '9th',
    'Preschool',   'Assoc-acdm',      '1st-4th',      '5th-6th']
Length: 16, dtype: str
marital.status unique values: <ArrowStringArray>
[   'Married-civ-spouse',         'Never-married',              'Divorced',
               'Widowed', 'Married-spouse-absent',             'Separated',
     'Married-AF-spouse']
Length: 7, dtype: str
occupation unique values: <ArrowStringArray>
[ 'Transport-moving',                 '?',      'Adm-clerical',
 'Machine-op-inspct',      'Tech-support',             'Sales',
   'Exec-managerial',    'Prof-specialty', 'Handlers-cleaners',
      'Craft-repair',   'Farming-fishing',     'Other-service',
   'Protective-serv',   'Priv-house-serv',      'Armed-Forces']
Length: 15, dtype: str
relationship unique values: <ArrowStringArray>
['Husband', 'Own-child', 'Not-in-family', 'Unmarried', 'Other-relative',
 'Wife']
Length: 6, dtype: str
race unique values: <ArrowStringArray>
['White', 'Asian-Pac-Islander', 'Black', 'Other', 'Amer-Indian-Eskimo']
Length: 5, dtype: str
sex unique values: <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
native.country unique values: <ArrowStringArray>
[             'United-States',                'Philippines',
                     'Canada',                    'Germany',
                    'Vietnam',                      'Italy',
                    'Jamaica',                       'Cuba',
                   'Columbia',                     'Taiwan',
                     'Mexico',                      'Japan',
                          '?',                    'Ireland',
                'Puerto-Rico',                      'India',
                       'Iran',                'El-Salvador',
                  'Guatemala',                      'Haiti',
 'Outlying-US(Guam-USVI-etc)',                      'China',
                   'Portugal',                    'England',
                      'South',                     'France',
                   'Honduras',         'Dominican-Republic',
                   'Cambodia',                       'Hong',
                     'Greece',                  'Nicaragua',
                    'Ecuador',                     'Poland',
                       'Peru',                       'Laos',
            'Trinadad&Tobago',                 'Yugoslavia',
                   'Thailand',                   'Scotland',
         'Holand-Netherlands']
Length: 41, dtype: str
income unique values: <ArrowStringArray>
['>50K', '<=50K']
Length: 2, dtype: str

In [36]:
train.replace("?", None, inplace=True)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,33,Private,155343,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
1,32,Private,165949,Bachelors,13,Divorced,Machine-op-inspct,Not-in-family,White,Female,0,1590,42,United-States,<=50K
2,18,NaN,173125,12th,8,Never-married,NaN,Own-child,White,Female,0,0,24,United-States,<=50K
3,31,Private,118551,9th,5,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
4,60,Self-emp-not-inc,170114,9th,5,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,1672,84,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26043,29,State-gov,71592,Some-college,10,Never-married,Adm-clerical,Unmarried,Asian-Pac-Islander,Female,0,0,40,Philippines,<=50K
26044,52,Private,94391,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
26045,43,Self-emp-not-inc,34007,Bachelors,13,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,70,United-States,>50K
26046,38,Private,133963,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
26047,43,Private,170214,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K

In [37]:
test.replace("?", None, inplace=True)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,46,Private,321327,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,7298,0,45,United-States,>50K
1,34,NaN,133861,HS-grad,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,25,United-States,<=50K
2,24,Private,289448,Assoc-voc,11,Never-married,Adm-clerical,Own-child,Asian-Pac-Islander,Female,0,0,40,Philippines,<=50K
3,33,Private,174789,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,50,United-States,<=50K
4,45,Self-emp-not-inc,34446,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6508,51,Private,117253,HS-grad,9,Widowed,Prof-specialty,Unmarried,White,Female,0,0,40,United-States,<=50K
6509,37,Private,126675,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K
6510,25,Private,186370,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K
6511,40,Local-gov,243580,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,48,United-States,<=50K
6512,22,Private,99829,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Female,0,0,30,United-States,<=50K

In [38]:
train.isna().sum()

age                  0
workclass         1479
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1485
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     486
income               0
dtype: int64

In [39]:
test.isna().sum()

age                 0
workclass         357
fnlwgt              0
education           0
education.num       0
marital.status      0
occupation        358
relationship        0
race                0
sex                 0
capital.gain        0
capital.loss        0
hours.per.week      0
native.country     97
income              0
dtype: int64

In [40]:
train.dropna(inplace=True)

In [41]:
test.dropna(inplace=True)

In [42]:
train.shape

(24099, 15)

In [43]:
test.shape

(6063, 15)

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
education_order = {
    "Preschool": 0,
    "1st-4th": 1,
    "5th-6th": 2,
    "7th-8th": 3,
    "9th": 4,
    "10th": 5,
    "11th": 6,
    "12th": 7,
    "HS-grad": 8,
    "Some-college": 9,
    "Assoc-voc": 10,
    "Assoc-acdm": 11,
    "Bachelors": 12,
    "Masters": 13,
    "Prof-school": 14,
    "Doctorate": 15
}

train["education"] = train["education"].map(education_order)
test["education"] = test["education"].map(education_order)

In [46]:
train["income"] = train["income"].map({
    "<=50K": 0,
    ">50K": 1
})

In [47]:
test["income"] = test["income"].map({
    "<=50K": 0,
    ">50K": 1
})

In [51]:
freq = train["native.country"].value_counts()
rare = freq[freq < 100].index

In [53]:
train["native.country"] = train["native.country"].replace(rare, "Other")

In [57]:
test["native.country"] = test["native.country"].apply(
    lambda x:x if x in freq.index and x not in rare else "Other")

In [58]:
train["native.country"].value_counts()

native.country
United-States    21962
Other             1392
Mexico             497
Philippines        142
Germany            106
Name: count, dtype: int64

In [59]:
test["native.country"].value_counts()

native.country
United-States    5542
Other             340
Mexico            113
Philippines        46
Germany            22
Name: count, dtype: int64

In [61]:
ohe_cols = [
    "workclass", "marital.status", "occupation",
    "relationship", "race", "sex", "native.country"
]

In [ ]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
ohe.fit(train[ohe_cols])

In [63]:
train_encoded = pd.DataFrame(
    ohe.transform(train[ohe_cols]),
    columns=ohe.get_feature_names_out(ohe_cols),
    index=train.index
)
test_encoded = pd.DataFrame(
    ohe.transform(test[ohe_cols]),
    columns=ohe.get_feature_names_out(ohe_cols),
    index=test.index
)

In [64]:
train.drop(columns=ohe_cols, inplace=True)
test.drop(columns=ohe_cols, inplace=True)

In [66]:
train =pd.concat([train, train_encoded], axis=1)
test = pd.concat([test, test_encoded], axis=1)

In [67]:
train.head()

,age,fnlwgt,education,education.num,capital.gain,capital.loss,hours.per.week,income,workclass_Federal-gov,workclass_Local-gov,...,race_Black,race_Other,race_White,sex_Female,sex_Male,native.country_Germany,native.country_Mexico,native.country_Other,native.country_Philippines,native.country_United-States
0,33,155343,8,9,0,0,40,0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,32,165949,12,13,0,1590,42,0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,31,118551,4,5,0,0,40,0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,60,170114,4,5,0,1672,84,0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5,30,79712,12,13,0,0,40,0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [68]:
num_cols = [
    "age", "fnlwgt", "capital.gain",
    "capital.loss", "hours.per.week", "education.num", "education"
]

In [69]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(train[num_cols])

StandardScaler()

In [70]:
train[num_cols] = scaler.transform(train[num_cols])
test[num_cols] = scaler.transform(test[num_cols])

In [72]:
train["income"].value_counts()

income
0    18055
1     6044
Name: count, dtype: int64

In [71]:
train.to_csv("train_clean.csv", index=False)
test.to_csv("test_clean.csv", index=False)